### ISSUE TITLE
Python @ property no longer displaying as yellow text in VSCode.

### ISSUE THREAD

**Issue by BMW1Addict** [danields761/vs-code-darcula20-theme#1]
Hello,

Love this color theme and use it daily/constantly in my Python development in VSCode.  I have latest version of VSCode and theme.  When I first installed and used the theme the "at property" decorator for a class displayed as yellow text (note: on preview of this issue in GitHub I cannot use the actual Python decorator syntax as GitHub thinks I am mentioning a user and capitalizes the "p" which is incorrect for Python).  I mistakenly typed "@Property" once (capital "P"), ran my code, got an error, corrected my code to lowercase "p" for "at property" and since then only the "@" is yellow and "property" is bold silver/"dirty-snow" white and no longer yellow.  Not sure if this is a theme issue or VSCode issue (not sure who is syntax highlighting this decorator as yellow?  Note. the corresponding "setter" decorator does display all in yellow. 

![Screen Shot 2022-10-12 at 6 53 47 AM](https://user-images.githubusercontent.com/81810872/195325333-bd7b0289-e2b9-44ec-a18a-722b83bf9c37.png)

If there is something I can update in my VSCode installation folder on my Mac please let know to get @ property to display all in yellow, I would greatly appreciate it. 

Please advise.  Thank you. 👍

**Comment by danields761** [comment]
@BMW1Addict , hello!

Thank you for the issue, but recently I had found theme which covers Python better and more consisten across other languages https://github.com/kevinvn1709/vscode-dracula-color-theme
